import product01 from "../assets/products/product-01.jpg";
import product02 from "../assets/products/product-02.jpg";
import product03 from "../assets/products/product-03.jpg";
import product04 from "../assets/products/product-04.jpg";
import product05 from "../assets/products/product-05.jpg";
import product06 from "../assets/products/product-06.jpg";
import product07 from "../assets/products/product-07.jpg";
import product08 from "../assets/products/product-08.jpg";
import product09 from "../assets/products/product-09.jpg";
import product10 from "../assets/products/product-10.jpg";
import product11 from "../assets/products/product-11.jpg";
import product12 from "../assets/products/product-12.jpg";
import product13 from "../assets/products/product-13.jpg";
import product14 from "../assets/products/product-14.jpg";
import product15 from "../assets/products/product-15.jpg";
import product16 from "../assets/products/product-16.jpg";
import product17 from "../assets/products/product-17.jpg";
import product18 from "../assets/products/product-18.jpg";
import product19 from "../assets/products/product-19.jpg";
import product20 from "../assets/products/product-20.jpg";
import product21 from "../assets/products/product-21.jpg";

const emoji = {
  cart: "\u{1F6D2}",
  chair: "\u{1FA91}",
  mug: "\u{2615}",
  organizer: "\u{1F4D2}",
  gloves: "\u{1F9E4}",
  knife: "\u{1F52A}",
  apron: "\u{1F455}",
  spoon: "\u{1F944}",
  mop: "\u{1F9F9}",
  lamp: "\u{1F4A1}",
  pillow: "\u{1F9F3}",
  cutting: "\u{1F52A}",
  spatula: "\u{1F372}",
  notebook: "\u{1F4D3}",
  pens: "\u{1F58A}",
  hoodie: "\u{1F9E5}",
  tshirt: "\u{1F455}",
  jeans: "\u{1F456}",
  hat: "\u{1F9E2}",
  planter: "\u{1FAB4}",
  tools: "\u{1F6E0}",
  watering: "\u{1F6BF}",
};

const products = [
  {
    id: 1,
    name: "Stylish Chair",
    price: 49.99,
    rating: 4.6,
    category: "Home",
    reviews: 124,
    emoji: emoji.chair,
    imageUrl: product01,
    imageAlt: "Wooden chair with a cushion near a window",
    description:
      "Handcrafted chair with a modern design, built for comfort and everyday use.",
    badge: "Bestseller",
  },
  {
    id: 2,
    name: "Ceramic Mug Set",
    price: 19.99,
    rating: 4.4,
    category: "Kitchen",
    reviews: 52,
    emoji: emoji.mug,
    imageUrl: product02,
    imageAlt: "White mug filled with coffee on a table",
    description: "Set of 4 ceramic mugs with a matte finish and heat-safe glaze.",
    badge: "New",
  },
  {
    id: 3,
    name: "Desk Organizer",
    price: 24.5,
    rating: 4.2,
    category: "Stationery",
    reviews: 31,
    emoji: emoji.organizer,
    imageUrl: product03,
    imageAlt: "Desk organizer with sticky notes and a pen",
    description: "Minimalist organizer for pens, notes, and small gadgets.",
    badge: "Popular",
  },
  {
    id: 4,
    name: "Garden Gloves",
    price: 12.0,
    rating: 4.1,
    category: "Garden",
    reviews: 18,
    emoji: emoji.gloves,
    imageUrl: product04,
    imageAlt: "Gardening gloves and tools on a woven fabric",
    description: "Durable gloves designed for comfort, grip, and easy cleanup.",
    badge: "Value",
  },
  {
    id: 5,
    name: "Bread Knife",
    price: 14.99,
    rating: 4.3,
    category: "Kitchen",
    reviews: 21,
    emoji: emoji.knife,
    imageUrl: product05,
    imageAlt: "Kitchen knife resting on a wooden cutting board",
    description: "Serrated bread knife with a balanced handle and clean slice.",
    badge: "Value",
  },
  {
    id: 6,
    name: "Kitchen Apron",
    price: 11.99,
    rating: 4.5,
    category: "Apparel",
    reviews: 19,
    emoji: emoji.apron,
    imageUrl: product06,
    imageAlt: "Brown kitchen apron hanging on a hook",
    description: "Adjustable apron designed for comfort and stain resistance.",
    badge: "Value",
  },
  {
    id: 7,
    name: "Silver Spoon Set",
    price: 39.0,
    rating: 4.6,
    category: "Kitchen",
    reviews: 76,
    emoji: emoji.spoon,
    imageUrl: product07,
    imageAlt: "Wooden spoon and fork on a beige cloth",
    description: "Polished stainless spoon set for daily dining and hosting.",
    badge: "Popular",
  },
  {
    id: 8,
    name: "Kitchen Mop",
    price: 18.0,
    rating: 4.0,
    category: "Kitchen",
    reviews: 44,
    emoji: emoji.mop,
    imageUrl: product08,
    imageAlt: "Yellow mop bucket with cleaning supplies",
    description: "Quick-dry mop with replaceable head for easy cleanup.",
    badge: "Value",
  },
  {
    id: 9,
    name: "Soft Glow Table Lamp",
    price: 34.99,
    rating: 4.5,
    category: "Home",
    reviews: 58,
    emoji: emoji.lamp,
    imageUrl: product09,
    imageAlt: "Brass and white table lamp in a dark room",
    description: "Warm ambient lamp with a soft-touch base and fabric shade.",
    badge: "New",
  },
  {
    id: 10,
    name: "Linen Throw Pillow",
    price: 16.75,
    rating: 4.2,
    category: "Home",
    reviews: 35,
    emoji: emoji.pillow,
    imageUrl: product10,
    imageAlt: "Neutral throw pillow resting on a white sofa",
    description: "Breathable linen pillow cover with a plush inner fill.",
    badge: "Value",
  },
  {
    id: 11,
    name: "Bamboo Cutting Board",
    price: 22.0,
    rating: 4.7,
    category: "Kitchen",
    reviews: 67,
    emoji: emoji.cutting,
    imageUrl: product11,
    imageAlt: "Wooden cutting board on a marble surface",
    description: "Knife-friendly cutting board with easy-grip edges.",
    badge: "Bestseller",
  },
  {
    id: 12,
    name: "Silicone Spatula Set",
    price: 13.5,
    rating: 4.4,
    category: "Kitchen",
    reviews: 49,
    emoji: emoji.spatula,
    imageUrl: product12,
    imageAlt: "Black spatula on a white background",
    description: "Heat-resistant spatulas built for nonstick cookware.",
    badge: "Popular",
  },
  {
    id: 13,
    name: "Dotted Notebook",
    price: 9.25,
    rating: 4.3,
    category: "Stationery",
    reviews: 28,
    emoji: emoji.notebook,
    imageUrl: product13,
    imageAlt: "Minimal notebook and pens on a white surface",
    description: "Lay-flat dotted notebook for sketches, plans, and notes.",
    badge: "New",
  },
  {
    id: 14,
    name: "Fine Tip Pen Set",
    price: 7.75,
    rating: 4.1,
    category: "Stationery",
    reviews: 40,
    emoji: emoji.pens,
    imageUrl: product14,
    imageAlt: "Assorted stationery and pens on a white desk",
    description: "Smooth-flow pens with smudge-resistant ink.",
    badge: "Value",
  },
  {
    id: 15,
    name: "Cozy Lounge Hoodie",
    price: 29.5,
    rating: 4.6,
    category: "Apparel",
    reviews: 83,
    emoji: emoji.hoodie,
    imageUrl: product15,
    imageAlt: "Folded hoodie on a wooden surface",
    description: "Soft fleece hoodie with a relaxed fit for everyday wear.",
    badge: "Bestseller",
  },
  {
    id: 16,
    name: "Everyday Tee",
    price: 15.0,
    rating: 4.2,
    category: "Clothing",
    reviews: 61,
    emoji: emoji.tshirt,
    imageUrl: product16,
    imageAlt: "Minimal flat lay of cotton t-shirts",
    description: "Lightweight cotton tee with a classic crew neck.",
    badge: "Popular",
  },
  {
    id: 17,
    name: "Straight Fit Jeans",
    price: 39.99,
    rating: 4.3,
    category: "Clothing",
    reviews: 54,
    emoji: emoji.jeans,
    imageUrl: product17,
    imageAlt: "Flat lay of denim jeans with accessories",
    description: "Durable denim with a straight fit and soft wash finish.",
    badge: "Value",
  },
  {
    id: 18,
    name: "Canvas Bucket Hat",
    price: 12.5,
    rating: 4.0,
    category: "Apparel",
    reviews: 29,
    emoji: emoji.hat,
    imageUrl: product18,
    imageAlt: "Beige hat in a minimalist flat lay with accessories",
    description: "Lightweight bucket hat with a sun-shade brim.",
    badge: "New",
  },
  {
    id: 19,
    name: "Ceramic Planter",
    price: 21.0,
    rating: 4.5,
    category: "Garden",
    reviews: 33,
    emoji: emoji.planter,
    imageUrl: product19,
    imageAlt: "Houseplant in a minimal gray pot",
    description: "Drainage-ready planter with a smooth glazed finish.",
    badge: "Popular",
  },
  {
    id: 20,
    name: "Garden Tool Kit",
    price: 26.5,
    rating: 4.4,
    category: "Garden",
    reviews: 46,
    emoji: emoji.tools,
    imageUrl: product20,
    imageAlt: "Flat lay of garden tools and green leaves",
    description: "Compact kit with a trowel, fork, and pruners.",
    badge: "Value",
  },
  {
    id: 21,
    name: "Watering Can",
    price: 17.25,
    rating: 4.2,
    category: "Garden",
    reviews: 38,
    emoji: emoji.watering,
    imageUrl: product21,
    imageAlt: "Metal watering can beside a wooden fence",
    description: "Easy-pour watering can with a balanced handle.",
    badge: "New",
  },
];

export default products;
